**Data Preprocessing Steps**

    Rescaling Data

    Standardizing Data

    Normalizing Data

    Binarizing Data

    One Hot Encoding (https://www.youtube.com/watch?v=v_4KWmkwmsU)

    Label Encoding


###ReScaling The Data

In [ ]:
import pandas, scipy, numpy
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import Normalizer
from sklearn.preprocessing import Binarizer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pandas.read_csv( 'https://mjnvsai.github.io/Machine_Learning/winequality-red.csv ',sep=';')
array = df.values
print(df.values)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]


In [ ]:
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

####Seperating Data Into Input and Output Components

In [ ]:
x = array[:,0:8]
y = array[:,8]
scaler = MinMaxScaler(feature_range=(0,1))
scaler

MinMaxScaler()

In [ ]:
rescaledX = scaler.fit_transform(x)
rescaledX

array([[0.24778761, 0.39726027, 0.        , ..., 0.14084507, 0.09893993,
        0.56754772],
       [0.28318584, 0.52054795, 0.        , ..., 0.33802817, 0.2155477 ,
        0.49412628],
       [0.28318584, 0.43835616, 0.04      , ..., 0.1971831 , 0.16961131,
        0.50881057],
       ...,
       [0.15044248, 0.26712329, 0.13      , ..., 0.3943662 , 0.12014134,
        0.41629956],
       [0.11504425, 0.35958904, 0.12      , ..., 0.43661972, 0.13427562,
        0.39647577],
       [0.12389381, 0.13013699, 0.47      , ..., 0.23943662, 0.12720848,
        0.3979442 ]])

In [ ]:
numpy.set_printoptions(precision = 3) #Setting precision for the output
rescaledX[0:5,:]

array([[0.248, 0.397, 0.   , 0.068, 0.107, 0.141, 0.099, 0.568],
       [0.283, 0.521, 0.   , 0.116, 0.144, 0.338, 0.216, 0.494],
       [0.283, 0.438, 0.04 , 0.096, 0.134, 0.197, 0.17 , 0.509],
       [0.584, 0.11 , 0.56 , 0.068, 0.105, 0.225, 0.191, 0.582],
       [0.248, 0.397, 0.   , 0.068, 0.107, 0.141, 0.099, 0.568]])

####Standarizing The Data

In [ ]:
scaler = StandardScaler().fit(x)
scaler

StandardScaler()

In [ ]:
rescaledX = scaler.transform(x)
rescaledX

array([[-0.528,  0.962, -1.391, ..., -0.466, -0.379,  0.558],
       [-0.299,  1.967, -1.391, ...,  0.873,  0.624,  0.028],
       [-0.299,  1.297, -1.186, ..., -0.084,  0.229,  0.134],
       ...,
       [-1.16 , -0.1  , -0.724, ...,  1.255, -0.197, -0.534],
       [-1.39 ,  0.655, -0.775, ...,  1.542, -0.075, -0.677],
       [-1.333, -1.217,  1.022, ...,  0.203, -0.136, -0.666]])

In [ ]:
rescaledX[0:5,:]

array([[-0.528,  0.962, -1.391, -0.453, -0.244, -0.466, -0.379,  0.558],
       [-0.299,  1.967, -1.391,  0.043,  0.224,  0.873,  0.624,  0.028],
       [-0.299,  1.297, -1.186, -0.169,  0.096, -0.084,  0.229,  0.134],
       [ 1.655, -1.384,  1.484, -0.453, -0.265,  0.108,  0.412,  0.664],
       [-0.528,  0.962, -1.391, -0.453, -0.244, -0.466, -0.379,  0.558]])

####Normalizing Th Data

In [ ]:
scaler = Normalizer().fit(x)
normalizedX = scaler.transform(x)
normalizedX[0:5,:]

array([[2.024e-01, 1.914e-02, 0.000e+00, 5.196e-02, 2.079e-03, 3.008e-01,
        9.299e-01, 2.729e-02],
       [1.083e-01, 1.222e-02, 0.000e+00, 3.611e-02, 1.361e-03, 3.472e-01,
        9.306e-01, 1.385e-02],
       [1.377e-01, 1.342e-02, 7.061e-04, 4.060e-02, 1.624e-03, 2.648e-01,
        9.533e-01, 1.760e-02],
       [1.767e-01, 4.416e-03, 8.833e-03, 2.997e-02, 1.183e-03, 2.681e-01,
        9.464e-01, 1.574e-02],
       [2.024e-01, 1.914e-02, 0.000e+00, 5.196e-02, 2.079e-03, 3.008e-01,
        9.299e-01, 2.729e-02]])

####Binarizing Data

In [ ]:
binarizer = Binarizer(threshold = 0.0).fit(x)
binaryX = binarizer.transform(x)
binaryX

array([[1., 1., 0., ..., 1., 1., 1.],
       [1., 1., 0., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [ ]:
binaryX[0:5,:]

array([[1., 1., 0., 1., 1., 1., 1., 1.],
       [1., 1., 0., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 0., 1., 1., 1., 1., 1.]])

####One Hot Encoding

In [ ]:
encoder = OneHotEncoder()
encoder.fit([[0,1,6,2],
[1,5,3,5],
[2,4,2,7],
[1,0,4,2]
])

OneHotEncoder()

**OneHotEncoder(categorical_features=’all’, dtype=<class ‘numpy.float64’>,
      handle_unknown=’error’, n_values=’auto’, sparse=True)**

In [ ]:
#encoder.transform([[2,4,3,4]]).toarray()

####Label Encoding

In [ ]:
label_encoder = LabelEncoder()
input_classes = ['Havells','Philips','Syska','Eveready','Lloyd']
label_encoder.fit(input_classes)

LabelEncoder()

In [ ]:
for i,item in enumerate(label_encoder.classes_):
  print(item,'-->',i)

Eveready --> 0
Havells --> 1
Lloyd --> 2
Philips --> 3
Syska --> 4


In [ ]:
df.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1599.000000       1599.000000  1599.000000     1599.000000   
mean        8.319637          0.527821     0.270976        2.538806   
std         1.741096          0.179060     0.194801        1.409928   
min         4.600000          0.120000     0.000000        0.900000   
25%         7.100000          0.390000     0.090000        1.900000   
50%         7.900000          0.520000     0.260000        2.200000   
75%         9.200000          0.640000     0.420000        2.600000   
max        15.900000          1.580000     1.000000       15.500000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1599.000000          1599.000000           1599.000000  1599.000000   
mean      0.087467            15.874922             46.467792     0.996747   
std       0.047065            10.460157             32.895324     0.001887   
min       0.012000             1.000000              6.000000     0.990070   
25%       0.070000             7.000000             22.000000     0.995600   
50%       0.079000            14.000000             38.000000     0.996750   
75%       0.090000            21.000000             62.000000     0.997835   
max       0.611000            72.000000            289.000000     1.003690   

                pH    sulphates      alcohol      quality  
count  1599.000000  1599.000000  1599.000000  1599.000000  
mean      3.311113     0.658149    10.422983     5.636023  
std       0.154386     0.169507     1.065668     0.807569  
min       2.740000     0.330000     8.400000     3.000000  
25%       3.210000     0.550000     9.500000     5.000000  
50%       3.310000     0.620000    10.200000     6.000000  
75%       3.400000     0.730000    11.100000     6.000000  
max       4.010000     2.000000    14.900000     8.000000